import { useEffect, useState } from 'react';
import Head from 'next/head';
import { Container, Row, Input } from '@nextui-org/react';
import styles from '../styles/Home.module.css';

import CountryList from '../components/CountryList';

export default function Home({ countries }) {
	const [query, setQuery] = useState('');
	const [searchCountries, setSearchedCountries] = useState([]);

	const handleSearchInput = (event) => {
		setQuery(event.target.value);
	};

	useEffect(() => {
		const searchCountries = async () => {
			const data = await fetch(`https://restcountries.com/v2/name/${query}`);
			const result = await data.json();
			console.log(result);
			setSearchedCountries(result);
		};
		if (query) {
			searchCountries();
		}
	}, [query]);

	return (
		<div>
			<Head>
				<title>Which World...</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>

			<main>
				<Container className={styles.main}>
					<Row css={{ paddingBottom: 40 }} justify='space-between'>
						<Input
							aria-label='search input'
							value={query}
							onChange={handleSearchInput}
							placeholder='Search for a country...'
						/>
						{'Drop down to filter by region'}
					</Row>

					<CountryList countries={countries} searchCountries={searchCountries} />
				</Container>
			</main>
		</div>
	);
}

export async function getStaticProps() {
	// Likely a better way to be doing this
	const data = await fetch('https://restcountries.com/v2/all');
	const countries = await data.json();
	return {
		props: {
			countries,
		},
	};
}
